### ISSUE TITLE
Service Register Error

### ISSUE THREAD

**Issue by winyh** [micro/examples#95] opened 2019-11-01 13:04 UTC
example： gretter
micro version: 1.7.0
mac book pro:10.14.6 

I do this list one by one.

`go run srv/main.go`

`go run cli/main.go`

`go run api/api.go`

`micro api --handler=api`

`curl http://localhost:8080/greeter/say/hello?name=John`

`go run web/web.go `

`micro web`

show error：
`{"id":"go.micro.api","code":500,"detail":"not found","status":"Internal Server Error"}`

but run script：
`go run cli/main.go  `

The result is ture.

Then I run script:
`micro list services`

Just get two services:

`go.micro.api
go.micro.web
`

`micro get service go.micro.api.greeter`
`micro get service go.micro.srv.greeter`

show error : 
Service not found

I think the service don't resgister successful, but I can't find the reason.
Who can give me some advice？Thank you！

**Comment by milosgajdos83** [comment] 2019-11-01 14:38
Duplicate of https://github.com/micro/go-micro/issues/900

**Closed by milosgajdos83** 2019-11-01 14:38 UTC
