### ISSUE TITLE
Understanding option in go-micro

### ISSUE THREAD

**Issue by itzmanish** [micro/examples#134] opened 2020-06-27 02:57 UTC
I am confused how to use options.
For eg:=
If I want a new auth then it will be initialized as 
```
// I want to initialize with a secret key, issuer and expiry time. How to get that?
av:= auth.NewAuth()
```

**Comment by asim** [comment] 2020-06-27 08:51
Duplicate of your other issue.

**Closed by asim** 2020-06-27 08:51 UTC

**Comment by itzmanish** [comment] 2020-06-28 02:10
okay. not using auth example we can take an example of broker or something else.
